
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("CheapChecker")

window.geometry("983x581")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 581,
    width = 983,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    983.0,
    581.0,
    fill="#E5E5E5",
    outline="")

canvas.create_rectangle(
    194.0,
    39.0,
    638.0,
    567.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    656.0,
    39.0,
    972.0,
    297.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    656.0,
    309.0,
    972.0,
    567.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    175.0,
    581.0,
    fill="#2ED47A",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    579.0,
    15.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=175.0,
    y=0.0,
    width=808.0,
    height=28.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    87.0,
    41.0,
    image=image_image_1
)

canvas.create_text(
    208.0,
    55.0,
    anchor="nw",
    text="These prices were found",
    fill="#192A3E",
    font=("Poppins Medium", 11 * -1)
)

canvas.create_text(
    39.0,
    91.0,
    anchor="nw",
    text="Shopping Cart",
    fill="#FFFFFF",
    font=("Poppins Medium", 11 * -1)
)

canvas.create_text(
    674.0,
    55.0,
    anchor="nw",
    text="This data was found based the prices",
    fill="#192A3E",
    font=("Poppins Medium", 11 * -1)
)

canvas.create_rectangle(
    656.0,
    91.0,
    972.0,
    92.0,
    fill="#EBEFF2",
    outline="")

canvas.create_text(
    674.0,
    325.0,
    anchor="nw",
    text="This is more data",
    fill="#192A3E",
    font=("Poppins Medium", 11 * -1)
)

canvas.create_rectangle(
    656.0,
    361.0,
    972.0,
    362.0,
    fill="#EBEFF2",
    outline="")

canvas.create_rectangle(
    194.0,
    91.0,
    638.0,
    92.0,
    fill="#EBEFF2",
    outline="")

canvas.create_rectangle(
    0.0,
    81.0,
    175.0,
    82.0,
    fill="#EBEFF2",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=869.58984375,
    y=0.13671875,
    width=113.34823608398438,
    height=29.5546875
)
window.resizable(False, False)
window.mainloop()
